name: Build Expo APK

on:
  push:
    branches:
      - main  # or your branch name

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install yarn
      run: npm install -g yarn

    - name: Install dependencies
      run: yarn install --frozen-lockfile

    - name: Login to Expo CLI
      env:
        EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}  # Set your Expo token in repo secrets
      run: |
        npm install -g expo-cli
        expo login --token $EXPO_TOKEN

    - name: Build Android APK
      env:
        EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
      run: expo build:android --type apk --non-interactive

    - name: Download APK artifact from Expo
      run: |
        # Expo outputs build status URL, you can poll or fetch APK URL from there
        # Here assuming the APK is downloaded manually or you have a script to fetch it
        echo "You need to add script here to download APK from Expo build URL"

    # Example: Upload local APK file (replace path if needed)
    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: app.apk
        path: android/app/build/outputs/apk/release/app-release.apk  # Adjust path if you have local build

