name: Build Expo Android APK (Managed Workflow)

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Setup Node.js 16 (expo-cli requires Node <=16)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # 3. Install Yarn
      - name: Install Yarn
        run: npm install -g yarn

      # 4. Install Expo CLI
      - name: Install Expo CLI
        run: npm install -g expo-cli

      # 5. Install dependencies
      - name: Install dependencies
        run: yarn install --frozen-lockfile

      # 6. Build APK with Expo Classic
      - name: Build APK
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        run: expo build:android -t apk --non-interactive

      # 7. Get APK URL (you must download manually from Expo)
      - name: Get APK URL
        run: expo url:apk --non-interactive
